// <auto-generated />
using System;
using BallClub.Repositories.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BallClub.Repositories.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("BallClub.Repositories.Messages.GameDTO", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PlayerIds")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Schedule")
                        .HasColumnType("DateTime");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<string>("TeamIds")
                        .HasColumnType("longtext");

                    b.HasKey("GameId")
                        .HasName("PK_Games");

                    b.HasIndex("GameId")
                        .HasDatabaseName("Idx_GameTeamId");

                    b.HasIndex("Schedule")
                        .HasDatabaseName("Idx_GameSchedule");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("Idx_GameSeason");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BallClub.Repositories.Messages.PlayerDTO", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int>("Blocks")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Loss")
                        .HasColumnType("int");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Rebounds")
                        .HasColumnType("int");

                    b.Property<string>("SocialMediaLinks")
                        .HasColumnType("longtext");

                    b.Property<int>("Steals")
                        .HasColumnType("int");

                    b.Property<string>("Suffix")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("PlayerId")
                        .HasName("PK_Players");

                    b.HasIndex("FirstName")
                        .HasDatabaseName("Idx_FirstName");

                    b.HasIndex("LastName")
                        .HasDatabaseName("Idx_LastName");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BallClub.Repositories.Messages.SeasonDTO", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SeasonId")
                        .HasName("PK_Seasons");

                    b.HasIndex("Name")
                        .HasDatabaseName("Idx_SeasonName");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("BallClub.Repositories.Messages.TeamDTO", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TeamId")
                        .HasName("PK_Teams");

                    b.HasIndex("Name")
                        .HasDatabaseName("Idx_TeamName");

                    b.ToTable("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
